[theme]
base = "dark"
primaryColor = "#58A6FF"
backgroundColor = "#0E1117"
secondaryBackgroundColor = "#161B22"
textColor = "#C9D1D9"
font = "sans serif"

[server]
headless = true
maxUploadSize = 200

[browser]
gatherUsageStats = false

[client]
showErrorDetails = true
toolbarMode = "minimal"
